require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JustificationsController do

  # This should return the minimal set of attributes required to create a valid
  # Justification. As you add validations to Justification, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all justifications as @justifications" do
      justification = Justification.create! valid_attributes
      get :index
      assigns(:justifications).should eq([justification])
    end
  end

  describe "GET show" do
    it "assigns the requested justification as @justification" do
      justification = Justification.create! valid_attributes
      get :show, :id => justification.id.to_s
      assigns(:justification).should eq(justification)
    end
  end

  describe "GET new" do
    it "assigns a new justification as @justification" do
      get :new
      assigns(:justification).should be_a_new(Justification)
    end
  end

  describe "GET edit" do
    it "assigns the requested justification as @justification" do
      justification = Justification.create! valid_attributes
      get :edit, :id => justification.id.to_s
      assigns(:justification).should eq(justification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Justification" do
        expect {
          post :create, :justification => valid_attributes
        }.to change(Justification, :count).by(1)
      end

      it "assigns a newly created justification as @justification" do
        post :create, :justification => valid_attributes
        assigns(:justification).should be_a(Justification)
        assigns(:justification).should be_persisted
      end

      it "redirects to the created justification" do
        post :create, :justification => valid_attributes
        response.should redirect_to(Justification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved justification as @justification" do
        # Trigger the behavior that occurs when invalid params are submitted
        Justification.any_instance.stub(:save).and_return(false)
        post :create, :justification => {}
        assigns(:justification).should be_a_new(Justification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Justification.any_instance.stub(:save).and_return(false)
        post :create, :justification => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested justification" do
        justification = Justification.create! valid_attributes
        # Assuming there are no other justifications in the database, this
        # specifies that the Justification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Justification.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => justification.id, :justification => {'these' => 'params'}
      end

      it "assigns the requested justification as @justification" do
        justification = Justification.create! valid_attributes
        put :update, :id => justification.id, :justification => valid_attributes
        assigns(:justification).should eq(justification)
      end

      it "redirects to the justification" do
        justification = Justification.create! valid_attributes
        put :update, :id => justification.id, :justification => valid_attributes
        response.should redirect_to(justification)
      end
    end

    describe "with invalid params" do
      it "assigns the justification as @justification" do
        justification = Justification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Justification.any_instance.stub(:save).and_return(false)
        put :update, :id => justification.id.to_s, :justification => {}
        assigns(:justification).should eq(justification)
      end

      it "re-renders the 'edit' template" do
        justification = Justification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Justification.any_instance.stub(:save).and_return(false)
        put :update, :id => justification.id.to_s, :justification => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested justification" do
      justification = Justification.create! valid_attributes
      expect {
        delete :destroy, :id => justification.id.to_s
      }.to change(Justification, :count).by(-1)
    end

    it "redirects to the justifications list" do
      justification = Justification.create! valid_attributes
      delete :destroy, :id => justification.id.to_s
      response.should redirect_to(justifications_url)
    end
  end

end
