require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NeedsController do

  # This should return the minimal set of attributes required to create a valid
  # Need. As you add validations to Need, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all needs as @needs" do
      need = Need.create! valid_attributes
      get :index
      assigns(:needs).should eq([need])
    end
  end

  describe "GET show" do
    it "assigns the requested need as @need" do
      need = Need.create! valid_attributes
      get :show, :id => need.id.to_s
      assigns(:need).should eq(need)
    end
  end

  describe "GET new" do
    it "assigns a new need as @need" do
      get :new
      assigns(:need).should be_a_new(Need)
    end
  end

  describe "GET edit" do
    it "assigns the requested need as @need" do
      need = Need.create! valid_attributes
      get :edit, :id => need.id.to_s
      assigns(:need).should eq(need)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Need" do
        expect {
          post :create, :need => valid_attributes
        }.to change(Need, :count).by(1)
      end

      it "assigns a newly created need as @need" do
        post :create, :need => valid_attributes
        assigns(:need).should be_a(Need)
        assigns(:need).should be_persisted
      end

      it "redirects to the created need" do
        post :create, :need => valid_attributes
        response.should redirect_to(Need.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved need as @need" do
        # Trigger the behavior that occurs when invalid params are submitted
        Need.any_instance.stub(:save).and_return(false)
        post :create, :need => {}
        assigns(:need).should be_a_new(Need)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Need.any_instance.stub(:save).and_return(false)
        post :create, :need => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested need" do
        need = Need.create! valid_attributes
        # Assuming there are no other needs in the database, this
        # specifies that the Need created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Need.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => need.id, :need => {'these' => 'params'}
      end

      it "assigns the requested need as @need" do
        need = Need.create! valid_attributes
        put :update, :id => need.id, :need => valid_attributes
        assigns(:need).should eq(need)
      end

      it "redirects to the need" do
        need = Need.create! valid_attributes
        put :update, :id => need.id, :need => valid_attributes
        response.should redirect_to(need)
      end
    end

    describe "with invalid params" do
      it "assigns the need as @need" do
        need = Need.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Need.any_instance.stub(:save).and_return(false)
        put :update, :id => need.id.to_s, :need => {}
        assigns(:need).should eq(need)
      end

      it "re-renders the 'edit' template" do
        need = Need.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Need.any_instance.stub(:save).and_return(false)
        put :update, :id => need.id.to_s, :need => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested need" do
      need = Need.create! valid_attributes
      expect {
        delete :destroy, :id => need.id.to_s
      }.to change(Need, :count).by(-1)
    end

    it "redirects to the needs list" do
      need = Need.create! valid_attributes
      delete :destroy, :id => need.id.to_s
      response.should redirect_to(needs_url)
    end
  end

end
